plugins {
    `java-platform`
}

val composeVersion = "1.7.0-SNAPSHOT"
val material3Version = "1.3.0-SNAPSHOT"
val material3AdaptiveVersion = "1.0.0-SNAPSHOT"
val material3AdaptiveNavSuiteVersion = "1.0.0-SNAPSHOT"

dependencies {
    constraints {
        api("androidx.compose.animation:animation:$composeVersion")
        api("androidx.compose.animation:animation-android:$composeVersion")
        api("androidx.compose.animation:animation-core:$composeVersion")
        api("androidx.compose.animation:animation-core-android:$composeVersion")
        api("androidx.compose.animation:animation-graphics:$composeVersion")
        api("androidx.compose.animation:animation-graphics-android:$composeVersion")
        api("androidx.compose.animation:animation-tooling-internal:$composeVersion")
        api("androidx.compose.foundation:foundation:$composeVersion")
        api("androidx.compose.foundation:foundation-android:$composeVersion")
        api("androidx.compose.foundation:foundation-layout:$composeVersion")
        api("androidx.compose.foundation:foundation-layout-android:$composeVersion")
        api("androidx.compose.material:material:$composeVersion")
        api("androidx.compose.material:material-android:$composeVersion")
        api("androidx.compose.material:material-icons-core:$composeVersion")
        api("androidx.compose.material:material-icons-core-android:$composeVersion")
        api("androidx.compose.material:material-icons-extended:$composeVersion")
        api("androidx.compose.material:material-icons-extended-android:$composeVersion")
        api("androidx.compose.material:material-ripple:$composeVersion")
        api("androidx.compose.material:material-ripple-android:$composeVersion")
        api("androidx.compose.material3:material3:$material3Version")
        api("androidx.compose.material3:material3-android:$material3Version")
        api("androidx.compose.material3:material3-adaptive-navigation-suite:$material3AdaptiveNavSuiteVersion")
        api("androidx.compose.material3:material3-adaptive-navigation-suite-android:$material3AdaptiveNavSuiteVersion")
        api("androidx.compose.material3:material3-window-size-class:$material3Version")
        api("androidx.compose.material3:material3-window-size-class-android:$material3Version")
        api("androidx.compose.material3.adaptive:adaptive:$material3AdaptiveVersion")
        api("androidx.compose.material3.adaptive:adaptive-android:$material3AdaptiveVersion")
        api("androidx.compose.material3.adaptive:adaptive-layout:$material3AdaptiveVersion")
        api("androidx.compose.material3.adaptive:adaptive-layout-android:$material3AdaptiveVersion")
        api("androidx.compose.material3.adaptive:adaptive-navigation:$material3AdaptiveVersion")
        api("androidx.compose.material3.adaptive:adaptive-navigation-android:$material3AdaptiveVersion")
        api("androidx.compose.runtime:runtime:$composeVersion")
        api("androidx.compose.runtime:runtime-android:$composeVersion")
        api("androidx.compose.runtime:runtime-livedata:$composeVersion")
        api("androidx.compose.runtime:runtime-rxjava2:$composeVersion")
        api("androidx.compose.runtime:runtime-rxjava3:$composeVersion")
        api("androidx.compose.runtime:runtime-saveable:$composeVersion")
        api("androidx.compose.runtime:runtime-saveable-android:$composeVersion")
        api("androidx.compose.ui:ui:$composeVersion")
        api("androidx.compose.ui:ui-android:$composeVersion")
        api("androidx.compose.ui:ui-android-stubs:$composeVersion")
        api("androidx.compose.ui:ui-geometry:$composeVersion")
        api("androidx.compose.ui:ui-geometry-android:$composeVersion")
        api("androidx.compose.ui:ui-graphics:$composeVersion")
        api("androidx.compose.ui:ui-graphics-android:$composeVersion")
        api("androidx.compose.ui:ui-test:$composeVersion")
        api("androidx.compose.ui:ui-test-android:$composeVersion")
        api("androidx.compose.ui:ui-test-junit4:$composeVersion")
        api("androidx.compose.ui:ui-test-junit4-android:$composeVersion")
        api("androidx.compose.ui:ui-test-manifest:$composeVersion")
        api("androidx.compose.ui:ui-text:$composeVersion")
        api("androidx.compose.ui:ui-text-android:$composeVersion")
        api("androidx.compose.ui:ui-text-google-fonts:$composeVersion")
        api("androidx.compose.ui:ui-tooling:$composeVersion")
        api("androidx.compose.ui:ui-tooling-android:$composeVersion")
        api("androidx.compose.ui:ui-tooling-data:$composeVersion")
        api("androidx.compose.ui:ui-tooling-data-android:$composeVersion")
        api("androidx.compose.ui:ui-tooling-preview:$composeVersion")
        api("androidx.compose.ui:ui-tooling-preview-android:$composeVersion")
        api("androidx.compose.ui:ui-unit:$composeVersion")
        api("androidx.compose.ui:ui-unit-android:$composeVersion")
        api("androidx.compose.ui:ui-util:$composeVersion")
        api("androidx.compose.ui:ui-util-android:$composeVersion")
        api("androidx.compose.ui:ui-viewbinding:$composeVersion")
    }
}